apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  namespace: hello
spec:
  selector:
    matchLabels:
      app: world
  replicas: 1
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: mgh35/hello-world:0.1.2
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: hello
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: world
